### ISSUE TITLE
os.umask('077') in python3

### ISSUE THREAD

**Issue by mdipierro** [linsomniac/bottlesession#6]
os.umask(077) does not work in python 3
os.umask('077') works with both 2 and 3.

**Comment by linsomniac** [comment]
Does it?

Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.umask('077')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: an integer is required

**Comment by linsomniac** [comment]
I think you must have meant int('077', 8), so I've changed it to that.  Thanks.
